
import { 
  Home, 
  Users, 
  BarChart3, 
  MessageSquare, 
  FileText, 
  Trash2,
  Building2,
  UserCheck,
  Shield,
  TrendingUp,
  Map,
  Activity,
  Droplets,
  Coins,
  Leaf,
  Target,
  DollarSign,
  Globe,
  Recycle
} from "lucide-react";

export const navItems = [
  {
    title: "Home",
    to: "/",
    icon: Home,
    variant: "default" as const,
  },
  {
    title: "Dashboard",
    to: "/dashboard",
    icon: BarChart3,
    variant: "ghost" as const,
  },
  {
    title: "User Types",
    to: "/user-types",
    icon: Users,
    variant: "ghost" as const,
  },
  {
    title: "Features",
    to: "/features",
    icon: Activity,
    variant: "ghost" as const,
  },
  {
    title: "About",
    to: "/about",
    icon: MessageSquare,
    variant: "ghost" as const,
  },
  {
    title: "Citizen Reports",
    to: "/citizen-reports",
    icon: FileText,
    variant: "ghost" as const,
  },
  {
    title: "Waste Entry",
    to: "/waste-entry",
    icon: Trash2,
    variant: "ghost" as const,
  },
  {
    title: "Marketplace",
    to: "/marketplace",
    icon: Building2,
    variant: "ghost" as const,
  },
  {
    title: "Plastic Credit Marketplace",
    to: "/plastic-credit-marketplace",
    icon: Recycle,
    variant: "ghost" as const,
  },
  {
    title: "Route Optimization",
    to: "/route-optimization",
    icon: Map,
    variant: "ghost" as const,
  },
  {
    title: "Carbon Credit Trading",
    to: "/carbon-credit-trading",
    icon: Leaf,
    variant: "ghost" as const,
  },
  {
    title: "Water Credit Trading",
    to: "/water-credit-trading",
    icon: Droplets,
    variant: "ghost" as const,
  },
  {
    title: "Green Bonds",
    to: "/green-bonds",
    icon: TrendingUp,
    variant: "ghost" as const,
  },
  {
    title: "ESG Reporting Tools",
    to: "/esg-reporting-tools",
    icon: Target,
    variant: "ghost" as const,
  },
  {
    title: "ESG Investment Tracking",
    to: "/esg-investment-tracking",
    icon: DollarSign,
    variant: "ghost" as const,
  },
  {
    title: "ESG Reporting Compliance",
    to: "/esg-reporting-compliance",
    icon: Shield,
    variant: "ghost" as const,
  },
  {
    title: "Micro Finance",
    to: "/micro-finance",
    icon: Coins,
    variant: "ghost" as const,
  },
  {
    title: "Enhanced Auth",
    to: "/enhanced-auth",
    icon: UserCheck,
    variant: "ghost" as const,
  },
];
